# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e106fb43b0bd2ff4846765262a6d4b8d3706cfa18c975a87587de440bb720ac7983228d60b1ea76120db0c775ebc390d246322c9ad8c362edfa3fdb3d907f9d

test:
  secret_key_base: 436f044fc95edc925678d29b700d2220228a5a4d919016a4b04130371127dd8bd589c9a477f9e6062e86dcfbe13ab02e8c31eeed455b7a27c4ba1287c2418c90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
